"""
AURA Autogenerated Protocol Buffers & gRPC Stubs.
=================================================
Contains dynamically compiled python modules mapping microservices contracts.
"""
from __future__ import annotations
