# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from shared.proto_gen import ai_pb2 as ai__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadModel = channel.unary_unary(
                '/aura.ai.v1.AIService/UploadModel',
                request_serializer=ai__pb2.UploadModelRequest.SerializeToString,
                response_deserializer=ai__pb2.ModelResponse.FromString,
                _registered_method=True)
        self.GetModel = channel.unary_unary(
                '/aura.ai.v1.AIService/GetModel',
                request_serializer=ai__pb2.GetModelRequest.SerializeToString,
                response_deserializer=ai__pb2.ModelResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/aura.ai.v1.AIService/ListModels',
                request_serializer=ai__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=ai__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.DeleteModel = channel.unary_unary(
                '/aura.ai.v1.AIService/DeleteModel',
                request_serializer=ai__pb2.DeleteModelRequest.SerializeToString,
                response_deserializer=ai__pb2.DeleteModelResponse.FromString,
                _registered_method=True)
        self.UpdateModelCompiled = channel.unary_unary(
                '/aura.ai.v1.AIService/UpdateModelCompiled',
                request_serializer=ai__pb2.UpdateModelCompiledRequest.SerializeToString,
                response_deserializer=ai__pb2.ModelResponse.FromString,
                _registered_method=True)
        self.UploadDataset = channel.unary_unary(
                '/aura.ai.v1.AIService/UploadDataset',
                request_serializer=ai__pb2.UploadDatasetRequest.SerializeToString,
                response_deserializer=ai__pb2.DatasetResponse.FromString,
                _registered_method=True)
        self.GetDataset = channel.unary_unary(
                '/aura.ai.v1.AIService/GetDataset',
                request_serializer=ai__pb2.GetDatasetRequest.SerializeToString,
                response_deserializer=ai__pb2.DatasetResponse.FromString,
                _registered_method=True)
        self.ListDatasets = channel.unary_unary(
                '/aura.ai.v1.AIService/ListDatasets',
                request_serializer=ai__pb2.ListDatasetsRequest.SerializeToString,
                response_deserializer=ai__pb2.ListDatasetsResponse.FromString,
                _registered_method=True)
        self.DeleteDataset = channel.unary_unary(
                '/aura.ai.v1.AIService/DeleteDataset',
                request_serializer=ai__pb2.DeleteDatasetRequest.SerializeToString,
                response_deserializer=ai__pb2.DeleteDatasetResponse.FromString,
                _registered_method=True)
        self.SetDatasetFile = channel.unary_unary(
                '/aura.ai.v1.AIService/SetDatasetFile',
                request_serializer=ai__pb2.SetDatasetFileRequest.SerializeToString,
                response_deserializer=ai__pb2.DatasetResponse.FromString,
                _registered_method=True)
        self.AssociateModelDataset = channel.unary_unary(
                '/aura.ai.v1.AIService/AssociateModelDataset',
                request_serializer=ai__pb2.AssociateModelDatasetRequest.SerializeToString,
                response_deserializer=ai__pb2.ModelResponse.FromString,
                _registered_method=True)
        self.UpdateModel = channel.unary_unary(
                '/aura.ai.v1.AIService/UpdateModel',
                request_serializer=ai__pb2.UpdateModelRequest.SerializeToString,
                response_deserializer=ai__pb2.ModelResponse.FromString,
                _registered_method=True)
        self.UpdateDataset = channel.unary_unary(
                '/aura.ai.v1.AIService/UpdateDataset',
                request_serializer=ai__pb2.UpdateDatasetRequest.SerializeToString,
                response_deserializer=ai__pb2.DatasetResponse.FromString,
                _registered_method=True)


class AIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateModelCompiled(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDatasets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDatasetFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssociateModelDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadModel,
                    request_deserializer=ai__pb2.UploadModelRequest.FromString,
                    response_serializer=ai__pb2.ModelResponse.SerializeToString,
            ),
            'GetModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModel,
                    request_deserializer=ai__pb2.GetModelRequest.FromString,
                    response_serializer=ai__pb2.ModelResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=ai__pb2.ListModelsRequest.FromString,
                    response_serializer=ai__pb2.ListModelsResponse.SerializeToString,
            ),
            'DeleteModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteModel,
                    request_deserializer=ai__pb2.DeleteModelRequest.FromString,
                    response_serializer=ai__pb2.DeleteModelResponse.SerializeToString,
            ),
            'UpdateModelCompiled': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateModelCompiled,
                    request_deserializer=ai__pb2.UpdateModelCompiledRequest.FromString,
                    response_serializer=ai__pb2.ModelResponse.SerializeToString,
            ),
            'UploadDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadDataset,
                    request_deserializer=ai__pb2.UploadDatasetRequest.FromString,
                    response_serializer=ai__pb2.DatasetResponse.SerializeToString,
            ),
            'GetDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDataset,
                    request_deserializer=ai__pb2.GetDatasetRequest.FromString,
                    response_serializer=ai__pb2.DatasetResponse.SerializeToString,
            ),
            'ListDatasets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDatasets,
                    request_deserializer=ai__pb2.ListDatasetsRequest.FromString,
                    response_serializer=ai__pb2.ListDatasetsResponse.SerializeToString,
            ),
            'DeleteDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDataset,
                    request_deserializer=ai__pb2.DeleteDatasetRequest.FromString,
                    response_serializer=ai__pb2.DeleteDatasetResponse.SerializeToString,
            ),
            'SetDatasetFile': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDatasetFile,
                    request_deserializer=ai__pb2.SetDatasetFileRequest.FromString,
                    response_serializer=ai__pb2.DatasetResponse.SerializeToString,
            ),
            'AssociateModelDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.AssociateModelDataset,
                    request_deserializer=ai__pb2.AssociateModelDatasetRequest.FromString,
                    response_serializer=ai__pb2.ModelResponse.SerializeToString,
            ),
            'UpdateModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateModel,
                    request_deserializer=ai__pb2.UpdateModelRequest.FromString,
                    response_serializer=ai__pb2.ModelResponse.SerializeToString,
            ),
            'UpdateDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDataset,
                    request_deserializer=ai__pb2.UpdateDatasetRequest.FromString,
                    response_serializer=ai__pb2.DatasetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aura.ai.v1.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aura.ai.v1.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.ai.v1.AIService/UploadModel',
            ai__pb2.UploadModelRequest.SerializeToString,
            ai__pb2.ModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.ai.v1.AIService/GetModel',
            ai__pb2.GetModelRequest.SerializeToString,
            ai__pb2.ModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.ai.v1.AIService/ListModels',
            ai__pb2.ListModelsRequest.SerializeToString,
            ai__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.ai.v1.AIService/DeleteModel',
            ai__pb2.DeleteModelRequest.SerializeToString,
            ai__pb2.DeleteModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateModelCompiled(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.ai.v1.AIService/UpdateModelCompiled',
            ai__pb2.UpdateModelCompiledRequest.SerializeToString,
            ai__pb2.ModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.ai.v1.AIService/UploadDataset',
            ai__pb2.UploadDatasetRequest.SerializeToString,
            ai__pb2.DatasetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.ai.v1.AIService/GetDataset',
            ai__pb2.GetDatasetRequest.SerializeToString,
            ai__pb2.DatasetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDatasets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.ai.v1.AIService/ListDatasets',
            ai__pb2.ListDatasetsRequest.SerializeToString,
            ai__pb2.ListDatasetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.ai.v1.AIService/DeleteDataset',
            ai__pb2.DeleteDatasetRequest.SerializeToString,
            ai__pb2.DeleteDatasetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDatasetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.ai.v1.AIService/SetDatasetFile',
            ai__pb2.SetDatasetFileRequest.SerializeToString,
            ai__pb2.DatasetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssociateModelDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.ai.v1.AIService/AssociateModelDataset',
            ai__pb2.AssociateModelDatasetRequest.SerializeToString,
            ai__pb2.ModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.ai.v1.AIService/UpdateModel',
            ai__pb2.UpdateModelRequest.SerializeToString,
            ai__pb2.ModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.ai.v1.AIService/UpdateDataset',
            ai__pb2.UpdateDatasetRequest.SerializeToString,
            ai__pb2.DatasetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
