# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from shared.proto_gen import compilation_pb2 as compilation__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in compilation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CompilationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CompileModel = channel.unary_unary(
                '/aura.compilation.v1.CompilationService/CompileModel',
                request_serializer=compilation__pb2.CompileModelRequest.SerializeToString,
                response_deserializer=compilation__pb2.CompileModelResponse.FromString,
                _registered_method=True)
        self.GetCompilationStatus = channel.unary_unary(
                '/aura.compilation.v1.CompilationService/GetCompilationStatus',
                request_serializer=compilation__pb2.GetCompilationStatusRequest.SerializeToString,
                response_deserializer=compilation__pb2.CompileModelResponse.FromString,
                _registered_method=True)
        self.TrainModel = channel.unary_unary(
                '/aura.compilation.v1.CompilationService/TrainModel',
                request_serializer=compilation__pb2.TrainModelRequest.SerializeToString,
                response_deserializer=compilation__pb2.TrainModelResponse.FromString,
                _registered_method=True)
        self.GetSupportedHardware = channel.unary_unary(
                '/aura.compilation.v1.CompilationService/GetSupportedHardware',
                request_serializer=compilation__pb2.GetSupportedHardwareRequest.SerializeToString,
                response_deserializer=compilation__pb2.GetSupportedHardwareResponse.FromString,
                _registered_method=True)
        self.GetSupportedSensors = channel.unary_unary(
                '/aura.compilation.v1.CompilationService/GetSupportedSensors',
                request_serializer=compilation__pb2.GetSupportedSensorsRequest.SerializeToString,
                response_deserializer=compilation__pb2.GetSupportedSensorsResponse.FromString,
                _registered_method=True)
        self.GetSupportedActuators = channel.unary_unary(
                '/aura.compilation.v1.CompilationService/GetSupportedActuators',
                request_serializer=compilation__pb2.GetSupportedActuatorsRequest.SerializeToString,
                response_deserializer=compilation__pb2.GetSupportedActuatorsResponse.FromString,
                _registered_method=True)
        self.GetSupportedOthers = channel.unary_unary(
                '/aura.compilation.v1.CompilationService/GetSupportedOthers',
                request_serializer=compilation__pb2.GetSupportedOthersRequest.SerializeToString,
                response_deserializer=compilation__pb2.GetSupportedOthersResponse.FromString,
                _registered_method=True)


class CompilationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CompileModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCompilationStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSupportedHardware(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSupportedSensors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSupportedActuators(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSupportedOthers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CompilationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CompileModel': grpc.unary_unary_rpc_method_handler(
                    servicer.CompileModel,
                    request_deserializer=compilation__pb2.CompileModelRequest.FromString,
                    response_serializer=compilation__pb2.CompileModelResponse.SerializeToString,
            ),
            'GetCompilationStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCompilationStatus,
                    request_deserializer=compilation__pb2.GetCompilationStatusRequest.FromString,
                    response_serializer=compilation__pb2.CompileModelResponse.SerializeToString,
            ),
            'TrainModel': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainModel,
                    request_deserializer=compilation__pb2.TrainModelRequest.FromString,
                    response_serializer=compilation__pb2.TrainModelResponse.SerializeToString,
            ),
            'GetSupportedHardware': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSupportedHardware,
                    request_deserializer=compilation__pb2.GetSupportedHardwareRequest.FromString,
                    response_serializer=compilation__pb2.GetSupportedHardwareResponse.SerializeToString,
            ),
            'GetSupportedSensors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSupportedSensors,
                    request_deserializer=compilation__pb2.GetSupportedSensorsRequest.FromString,
                    response_serializer=compilation__pb2.GetSupportedSensorsResponse.SerializeToString,
            ),
            'GetSupportedActuators': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSupportedActuators,
                    request_deserializer=compilation__pb2.GetSupportedActuatorsRequest.FromString,
                    response_serializer=compilation__pb2.GetSupportedActuatorsResponse.SerializeToString,
            ),
            'GetSupportedOthers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSupportedOthers,
                    request_deserializer=compilation__pb2.GetSupportedOthersRequest.FromString,
                    response_serializer=compilation__pb2.GetSupportedOthersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aura.compilation.v1.CompilationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aura.compilation.v1.CompilationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CompilationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CompileModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.compilation.v1.CompilationService/CompileModel',
            compilation__pb2.CompileModelRequest.SerializeToString,
            compilation__pb2.CompileModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCompilationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.compilation.v1.CompilationService/GetCompilationStatus',
            compilation__pb2.GetCompilationStatusRequest.SerializeToString,
            compilation__pb2.CompileModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrainModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.compilation.v1.CompilationService/TrainModel',
            compilation__pb2.TrainModelRequest.SerializeToString,
            compilation__pb2.TrainModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSupportedHardware(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.compilation.v1.CompilationService/GetSupportedHardware',
            compilation__pb2.GetSupportedHardwareRequest.SerializeToString,
            compilation__pb2.GetSupportedHardwareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSupportedSensors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.compilation.v1.CompilationService/GetSupportedSensors',
            compilation__pb2.GetSupportedSensorsRequest.SerializeToString,
            compilation__pb2.GetSupportedSensorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSupportedActuators(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.compilation.v1.CompilationService/GetSupportedActuators',
            compilation__pb2.GetSupportedActuatorsRequest.SerializeToString,
            compilation__pb2.GetSupportedActuatorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSupportedOthers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.compilation.v1.CompilationService/GetSupportedOthers',
            compilation__pb2.GetSupportedOthersRequest.SerializeToString,
            compilation__pb2.GetSupportedOthersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
