# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: deployment.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'deployment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64\x65ployment.proto\x12\x12\x61ura.deployment.v1\"_\n\x17\x43reateDeploymentRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x11\n\tscript_id\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\"\"\n\x14GetDeploymentRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x18\n\x16ListDeploymentsRequest\"1\n\x1cListDeviceDeploymentsRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\"\xc2\x01\n\x12\x44\x65ploymentResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x10\n\x08model_id\x18\x03 \x01(\t\x12\x11\n\tscript_id\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x0f\n\x07sent_at\x18\x06 \x01(\t\x12\x12\n\nrunning_at\x18\x07 \x01(\t\x12\x11\n\terror_msg\x18\x08 \x01(\t\x12\x12\n\ncreated_at\x18\t \x01(\t\x12\x0c\n\x04name\x18\n \x01(\t\"V\n\x17ListDeploymentsResponse\x12;\n\x0b\x64\x65ployments\x18\x01 \x03(\x0b\x32&.aura.deployment.v1.DeploymentResponse2\xc3\x03\n\x11\x44\x65ploymentService\x12g\n\x10\x43reateDeployment\x12+.aura.deployment.v1.CreateDeploymentRequest\x1a&.aura.deployment.v1.DeploymentResponse\x12\x61\n\rGetDeployment\x12(.aura.deployment.v1.GetDeploymentRequest\x1a&.aura.deployment.v1.DeploymentResponse\x12j\n\x0fListDeployments\x12*.aura.deployment.v1.ListDeploymentsRequest\x1a+.aura.deployment.v1.ListDeploymentsResponse\x12v\n\x15ListDeviceDeployments\x12\x30.aura.deployment.v1.ListDeviceDeploymentsRequest\x1a+.aura.deployment.v1.ListDeploymentsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'deployment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEDEPLOYMENTREQUEST']._serialized_start=40
  _globals['_CREATEDEPLOYMENTREQUEST']._serialized_end=135
  _globals['_GETDEPLOYMENTREQUEST']._serialized_start=137
  _globals['_GETDEPLOYMENTREQUEST']._serialized_end=171
  _globals['_LISTDEPLOYMENTSREQUEST']._serialized_start=173
  _globals['_LISTDEPLOYMENTSREQUEST']._serialized_end=197
  _globals['_LISTDEVICEDEPLOYMENTSREQUEST']._serialized_start=199
  _globals['_LISTDEVICEDEPLOYMENTSREQUEST']._serialized_end=248
  _globals['_DEPLOYMENTRESPONSE']._serialized_start=251
  _globals['_DEPLOYMENTRESPONSE']._serialized_end=445
  _globals['_LISTDEPLOYMENTSRESPONSE']._serialized_start=447
  _globals['_LISTDEPLOYMENTSRESPONSE']._serialized_end=533
  _globals['_DEPLOYMENTSERVICE']._serialized_start=536
  _globals['_DEPLOYMENTSERVICE']._serialized_end=987
# @@protoc_insertion_point(module_scope)
