# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from shared.proto_gen import monitoring_pb2 as monitoring__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in monitoring_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MonitoringServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDeviceState = channel.unary_unary(
                '/aura.monitoring.v1.MonitoringService/GetDeviceState',
                request_serializer=monitoring__pb2.GetDeviceStateRequest.SerializeToString,
                response_deserializer=monitoring__pb2.DeviceStateResponse.FromString,
                _registered_method=True)
        self.ListDeviceStates = channel.unary_unary(
                '/aura.monitoring.v1.MonitoringService/ListDeviceStates',
                request_serializer=monitoring__pb2.ListDeviceStatesRequest.SerializeToString,
                response_deserializer=monitoring__pb2.ListDeviceStatesResponse.FromString,
                _registered_method=True)
        self.GetInferenceResults = channel.unary_unary(
                '/aura.monitoring.v1.MonitoringService/GetInferenceResults',
                request_serializer=monitoring__pb2.GetInferenceResultsRequest.SerializeToString,
                response_deserializer=monitoring__pb2.GetInferenceResultsResponse.FromString,
                _registered_method=True)
        self.DeleteDeviceState = channel.unary_unary(
                '/aura.monitoring.v1.MonitoringService/DeleteDeviceState',
                request_serializer=monitoring__pb2.DeleteDeviceStateRequest.SerializeToString,
                response_deserializer=monitoring__pb2.DeleteDeviceStateResponse.FromString,
                _registered_method=True)


class MonitoringServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDeviceState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDeviceStates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInferenceResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDeviceState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonitoringServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDeviceState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceState,
                    request_deserializer=monitoring__pb2.GetDeviceStateRequest.FromString,
                    response_serializer=monitoring__pb2.DeviceStateResponse.SerializeToString,
            ),
            'ListDeviceStates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDeviceStates,
                    request_deserializer=monitoring__pb2.ListDeviceStatesRequest.FromString,
                    response_serializer=monitoring__pb2.ListDeviceStatesResponse.SerializeToString,
            ),
            'GetInferenceResults': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInferenceResults,
                    request_deserializer=monitoring__pb2.GetInferenceResultsRequest.FromString,
                    response_serializer=monitoring__pb2.GetInferenceResultsResponse.SerializeToString,
            ),
            'DeleteDeviceState': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDeviceState,
                    request_deserializer=monitoring__pb2.DeleteDeviceStateRequest.FromString,
                    response_serializer=monitoring__pb2.DeleteDeviceStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aura.monitoring.v1.MonitoringService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aura.monitoring.v1.MonitoringService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MonitoringService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDeviceState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.monitoring.v1.MonitoringService/GetDeviceState',
            monitoring__pb2.GetDeviceStateRequest.SerializeToString,
            monitoring__pb2.DeviceStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDeviceStates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.monitoring.v1.MonitoringService/ListDeviceStates',
            monitoring__pb2.ListDeviceStatesRequest.SerializeToString,
            monitoring__pb2.ListDeviceStatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInferenceResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.monitoring.v1.MonitoringService/GetInferenceResults',
            monitoring__pb2.GetInferenceResultsRequest.SerializeToString,
            monitoring__pb2.GetInferenceResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDeviceState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.monitoring.v1.MonitoringService/DeleteDeviceState',
            monitoring__pb2.DeleteDeviceStateRequest.SerializeToString,
            monitoring__pb2.DeleteDeviceStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
