# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: script.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'script.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cscript.proto\x12\x0e\x61ura.script.v1\"u\n\x13UploadScriptRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x12\n\nscript_key\x18\x04 \x01(\t\x12\x15\n\rscript_sha256\x18\x05 \x01(\t\"\x1e\n\x10GetScriptRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x14\n\x12ListScriptsRequest\"!\n\x13\x44\x65leteScriptRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\'\n\x14\x44\x65leteScriptResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x90\x01\n\x0eScriptResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x10\n\x08language\x18\x04 \x01(\t\x12\x12\n\nscript_key\x18\x05 \x01(\t\x12\x15\n\rscript_sha256\x18\x06 \x01(\t\x12\x12\n\ncreated_at\x18\x07 \x01(\t\"F\n\x13ListScriptsResponse\x12/\n\x07scripts\x18\x01 \x03(\x0b\x32\x1e.aura.script.v1.ScriptResponse2\xe6\x02\n\rScriptService\x12S\n\x0cUploadScript\x12#.aura.script.v1.UploadScriptRequest\x1a\x1e.aura.script.v1.ScriptResponse\x12M\n\tGetScript\x12 .aura.script.v1.GetScriptRequest\x1a\x1e.aura.script.v1.ScriptResponse\x12V\n\x0bListScripts\x12\".aura.script.v1.ListScriptsRequest\x1a#.aura.script.v1.ListScriptsResponse\x12Y\n\x0c\x44\x65leteScript\x12#.aura.script.v1.DeleteScriptRequest\x1a$.aura.script.v1.DeleteScriptResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'script_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADSCRIPTREQUEST']._serialized_start=32
  _globals['_UPLOADSCRIPTREQUEST']._serialized_end=149
  _globals['_GETSCRIPTREQUEST']._serialized_start=151
  _globals['_GETSCRIPTREQUEST']._serialized_end=181
  _globals['_LISTSCRIPTSREQUEST']._serialized_start=183
  _globals['_LISTSCRIPTSREQUEST']._serialized_end=203
  _globals['_DELETESCRIPTREQUEST']._serialized_start=205
  _globals['_DELETESCRIPTREQUEST']._serialized_end=238
  _globals['_DELETESCRIPTRESPONSE']._serialized_start=240
  _globals['_DELETESCRIPTRESPONSE']._serialized_end=279
  _globals['_SCRIPTRESPONSE']._serialized_start=282
  _globals['_SCRIPTRESPONSE']._serialized_end=426
  _globals['_LISTSCRIPTSRESPONSE']._serialized_start=428
  _globals['_LISTSCRIPTSRESPONSE']._serialized_end=498
  _globals['_SCRIPTSERVICE']._serialized_start=501
  _globals['_SCRIPTSERVICE']._serialized_end=859
# @@protoc_insertion_point(module_scope)
