# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from shared.proto_gen import script_pb2 as script__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in script_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScriptServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadScript = channel.unary_unary(
                '/aura.script.v1.ScriptService/UploadScript',
                request_serializer=script__pb2.UploadScriptRequest.SerializeToString,
                response_deserializer=script__pb2.ScriptResponse.FromString,
                _registered_method=True)
        self.GetScript = channel.unary_unary(
                '/aura.script.v1.ScriptService/GetScript',
                request_serializer=script__pb2.GetScriptRequest.SerializeToString,
                response_deserializer=script__pb2.ScriptResponse.FromString,
                _registered_method=True)
        self.ListScripts = channel.unary_unary(
                '/aura.script.v1.ScriptService/ListScripts',
                request_serializer=script__pb2.ListScriptsRequest.SerializeToString,
                response_deserializer=script__pb2.ListScriptsResponse.FromString,
                _registered_method=True)
        self.DeleteScript = channel.unary_unary(
                '/aura.script.v1.ScriptService/DeleteScript',
                request_serializer=script__pb2.DeleteScriptRequest.SerializeToString,
                response_deserializer=script__pb2.DeleteScriptResponse.FromString,
                _registered_method=True)


class ScriptServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListScripts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScriptServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadScript': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadScript,
                    request_deserializer=script__pb2.UploadScriptRequest.FromString,
                    response_serializer=script__pb2.ScriptResponse.SerializeToString,
            ),
            'GetScript': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScript,
                    request_deserializer=script__pb2.GetScriptRequest.FromString,
                    response_serializer=script__pb2.ScriptResponse.SerializeToString,
            ),
            'ListScripts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListScripts,
                    request_deserializer=script__pb2.ListScriptsRequest.FromString,
                    response_serializer=script__pb2.ListScriptsResponse.SerializeToString,
            ),
            'DeleteScript': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteScript,
                    request_deserializer=script__pb2.DeleteScriptRequest.FromString,
                    response_serializer=script__pb2.DeleteScriptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aura.script.v1.ScriptService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aura.script.v1.ScriptService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScriptService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.script.v1.ScriptService/UploadScript',
            script__pb2.UploadScriptRequest.SerializeToString,
            script__pb2.ScriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.script.v1.ScriptService/GetScript',
            script__pb2.GetScriptRequest.SerializeToString,
            script__pb2.ScriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListScripts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.script.v1.ScriptService/ListScripts',
            script__pb2.ListScriptsRequest.SerializeToString,
            script__pb2.ListScriptsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aura.script.v1.ScriptService/DeleteScript',
            script__pb2.DeleteScriptRequest.SerializeToString,
            script__pb2.DeleteScriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
